# Change these first
owner: plone
repo: plone-ping # The name of this repository

sites:
  - name: Plone.org
    url: https://plone.org
  - name: Documentation
    url: https://docs.plone.org
  - name: Training
    url: https://training.plone.org
  - name: Community
    url: https://community.plone.org
  - name: CI (Jenkins)
    url: https://jenkins.plone.org
  - name: Static Files
    url: https://dist.plone.org
  # Regional Plone Sites
  - name: Plone Brasil
    url: https://plone.org.br
  # Conference Sites
  - name: Plone Conference 2026
    url: https://2026.ploneconf.org
  - name: Plone Conference 2025
    url: https://2025.ploneconf.org
  - name: Plone Conference 2024
    url: https://2024.ploneconf.org
  # Demo
  - name: Demo Site
    url: https://demo.plone.org


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.plone.org
  # baseUrl: /your-repo-name
  logoUrl: /images/icon.svg
  favicon: /images/favicon-32x32.png
  faviconSvg: /images/icon.svg
  name: Plone Status Page
  introTitle: "**Plone Status Page**"
  introMessage: Status of services and sites maintained by the Plone community. This solution is built using [Upptime](https://upptime.js.org/).
  navbar:
    - title: Status
      href: /
    - title: Plone Foundation
      href: https://plone.org/foundation

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
